[project]
name = "trading-nanovllm"
version = "0.1.0"
description = "Lightweight LLM for trading tasks"
dependencies = [
    "torch>=2.0.0",
    "transformers>=4.35.0",
    "numpy>=1.26.0",
    "tqdm>=4.66.0",
]

[build-system]
requires = ["setuptools>=61.0"]
<<<<<<< HEAD
build-backend = "setuptools.build_meta"
=======
<<<<<<< HEAD
build-backend = "setuptools.build_meta"
=======
build-backend = "setuptools.build_meta"
>>>>>>> 5bcd18a (Add project structure, core LLM, trading utilities, and scripts)
>>>>>>> 3d893a2 (Add project structure, core LLM, trading utilities, and scripts)
